import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
const styles=[readFileSync(new URL('../src/ui/styles.css',import.meta.url),'utf8'),readFileSync(new URL('../src/ui/mobile-overrides.css',import.meta.url),'utf8')].join('\n');
const primaryDrawPlacement=readFileSync(new URL('../src/ui/primary-draw-placement.ts',import.meta.url),'utf8');
const drawAnimation=readFileSync(new URL('../src/ui/draw-animation.ts',import.meta.url),'utf8');
const drawView=readFileSync(new URL('../src/ui/draw-view.ts',import.meta.url),'utf8');
const attractionView=readFileSync(new URL('../src/ui/attraction-view.ts',import.meta.url),'utf8');
const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');
describe('Random Seoul responsive visual contract',()=>{
  it('stacks restaurant result cards vertically on phones',()=>expect(styles).toContain('grid-template-columns:1fr!important'));
  it('keeps touch-sized restaurant map buttons',()=>{expect(styles).toContain('min-height:44px');expect(styles).toContain('width:100%')});
  it('keeps dense result cards',()=>{expect(styles).toContain('min-height:176px');expect(styles).toContain('min-height:164px');expect(styles).toContain('min-height:96px');expect(styles).toContain('min-height:154px')});
  it('uses distinct pastel surfaces',()=>{expect(styles).toContain('.line-panel{background:#dfeecb}');expect(styles).toContain('.station-panel{background:#dbeaf1}');expect(styles).toContain('.food-panel{background:#f4dfc5}')});
  it('uses whole next-result card as target',()=>{expect(styles).toContain('.panel.next-draw>.draw-btn.integrated');expect(primaryDrawPlacement).toContain("panel.classList.add('next-draw')")});
  it('keeps strong outline only on active card',()=>{expect(styles).toContain('border:2px solid var(--dark)!important');expect(styles).toContain('content:"⚄"')});
  it('uses a long result reveal',()=>{expect(drawAnimation).toContain("translateY(-12px) scale(1.09)");expect(drawAnimation).toContain('duration:900')});
  it('places compact attractions after draw panels',()=>{expect(attractionView).toContain("panels.insertAdjacentElement('afterend', section)");expect(attractionView).toContain("'추천 명소'");expect(styles).toContain('#attraction_section .attraction-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}')});
  it('defers restaurant lookup until requested',()=>{expect(main).toContain("button.textContent = '추천 식당 보기'");expect(main).toContain("restaurantRequest.button.addEventListener('click'");expect(main).toContain('await controller.loadRecommendations()');expect(main).toContain("document.body.dataset.selftestDeferredRestaurants = 'true'")});
  it('smooth-scrolls after restaurant results settle',()=>{expect(main.indexOf("scrollIntoView({")).toBeGreaterThan(main.indexOf('await controller.loadRecommendations()'));expect(main).toContain("behavior: selfTestMode ? 'auto' : 'smooth'")});
  it('uses dedicated restaurant CTA',()=>{expect(styles).toContain('.restaurant-request-btn{width:100%;min-height:48px')});
  it('uses concise labels',()=>{expect(drawView).toContain("textContent = '노선'");expect(drawView).toContain("textContent = '역'");expect(drawView).toContain("textContent = '음식'")});
});
